### ISSUE TITLE
Create read me for Automation project

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-at-automation-driver#46]
Create read me for this project that will include: 

- AT-Driver VoiceOver Implementation
- Automation UI Improvements 
- Firefox integration NVDA 
- Safari and Chrome  integration
- TBC - reports that are run and have same responses as before we would like to show them as final  and if there are differences we would also define where to bring it.

**Comment by jugglinmike** [comment]
[Here is a draft for public
review.](https://docs.google.com/document/d/19kJWkF2IrWYAwg3s3VN_e7irCh_7AFUSMfGhNGkeTmA/edit)

**Comment by ccanash** [comment]
Closing as this task is now being tracked here https://github.com/w3c/aria-at-app/issues/1059 and opened for discussion
